pipeline {

  agent any

  stages {

    stage('Checkout') {
      steps {
        git 'https://github.com/USERNAME/repo.git'
      }
    }

    stage('SonarQube Scan') {
      steps {
        sh 'sonar-scanner'
      }
    }

    stage('Quality Gate') {
      steps {
        waitForQualityGate abortPipeline: true
      }
    }

    stage('Docker Build') {
      steps {
        sh 'docker build -t devsecops-app .'
      }
    }

    stage('Trivy Scan') {
      steps {
        sh 'trivy image devsecops-app'
      }
    }

    stage('Docker Push') {
      steps {
        sh 'docker push USERNAME/devsecops-app:latest'
      }
    }
  }
}
